repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.1'
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md,markdown']
      - id: end-of-file-fixer
      - id: check-yaml

  # isort should run before black as black sometimes tweaks the isort output
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: '21.10b0'
    hooks:
      - id: black
        exclude: ^examples/

  # - repo: https://github.com/PyCQA/flake8
  #   rev: '3.9.2'
  #   hooks:
  #     - id: flake8

  - repo: https://github.com/csachs/pyproject-flake8
    rev: 'v0.0.1a2.post1'
    hooks:
      - id: pyproject-flake8  # pflake8
