ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v5.0.0'
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md,markdown']
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/PyCQA/isort
    rev: '6.0.0'
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: '25.1.0'
    hooks:
      - id: black
        exclude: ^examples/

  # - repo: https://github.com/PyCQA/flake8
  #   rev: '3.9.2'
  #   hooks:
  #     - id: flake8

  - repo: https://github.com/csachs/pyproject-flake8
    rev: 'v7.0.0'
    hooks:
      - id: pyproject-flake8  # pflake8
